<p class="justificado msgAlerta">Importante salientar que cada foto publicada no site captura.me está vinculada ao usuário cadastrado, onde é de responsabilidade do usuário ter como provar que foi o autor da imagem enviada onde izenta o captura.me de toda e qualquer punição legal aplicada apenas ao usuário responsável pelo envio da imagem.</p>

<h4>Registro</h4>
<p class="justificado paragrafoDefault">Composto de um formulário padrão, onde o mesmo consiste em informar os dados:</p>
<ul>
    <li>Nome, login, senha, cpf, rg e email.</li>
</ul>

<h4>Facebook</h4>
<p class="justificado paragrafoDefault">É Possível agilizar o processo de cadastro vinculando sua conta do captura.me com o seu perfil do facebook, onde consiste em estar logado no facebook e disponibilizar seus dados para que possa ser feita a inscrição no captura.me de uma forma mais ágil.</p>

<p class="centralizado paragrafoDefault">Entrar -- Registrar -- Facebook</p>