<?php $this->tituloHelper()->setTitulo('Calendário'); ?>

<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Eventos Captura.Me</h2>
        <h2 class='subtitulo'>Lista de eventos que possívelmente o Captura.Me vai estar</h2>
    </bloquenote>
    <article>
        <div id="calendario" align="center">
            <iframe src="https://www.google.com/calendar/embed?title=Eventos%20Captura.Me&amp;src=sugestoes%40captura.me&amp;showTitle=0&amp;showNav=0&amp;showDate=0&amp;showCalendars=0&amp;height=400&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;ctz=America%2FFortaleza" style=" border-width:0 " width="520" height="360" frameborder="0" scrolling="no"></iframe>
        </div>
    </article>
</div>

