<?php $this->tituloHelper()->setTitulo('Editar Perfil'); ?>
<div class='parteConteudo'>
    <bloquenote class="editar">
        <h2 class='titulo'>Editar Perfil</h2>
        <h2 class='subtitulo'>Editando dados do usuário no Captura.Me</h2>
    </bloquenote>
    <article>
        <?php $form = $this->form;  $form->setAttribute('action', $this->url('editar-usuario')); $form->prepare(); ?>
        <?php if($form->getMessages()): ?>
        <bloquenote>
            <?php foreach($form->getMessages() as $i => $element): ?>
                <p><?php echo "Erro: [" . $this->formLabel($form->get($i)) . '] ' .  implode(', ', $form->get($i)->getMessages()); ?></p>
            <?php endforeach; ?>
        </bloquenote>
        <?php endif;?>
        <?php echo $this->form()->openTag($form); ?>
        <ul class="ladoalado">
            <li><?php echo $this->formLabel($form->get('nome')); ?><?php echo $this->formElement($form->get('nome')); ?></li>
            <li><?php echo $this->formLabel($form->get('email')); ?><?php echo $this->formElement($form->get('email')); ?></li>
            <li><?php echo $this->formLabel($form->get('telefone')); ?><?php echo $this->formElement($form->get('telefone')); ?></li>
            <li><?php echo $this->formSubmit($form->get('enviar')); ?></li>
        </ul>
        <?php echo $this->form()->closeTag(); ?>
    </article>  
</div>