<?php $this->tituloHelper()->setTitulo('Modificar Senha'); ?>
<div class='parteConteudo'>
    <bloquenote class="modificarSenha">
        <h2 class='titulo'>Modificar Senha</h2>
        <h2 class='subtitulo'>Local onde é possível modificar sua senha</h2>
    </bloquenote>
    <article>
        <?php $form = $this->form;  $form->setAttribute('action', $this->url('modificar-senha')); $form->prepare(); ?>
        <?php if($form->getMessages()): ?>
        <bloquenote>
            <?php foreach($form->getMessages() as $i => $element): ?>
                <p><?php echo "Erro: [" . $this->formLabel($form->get($i)) . '] ' .  implode(', ', $form->get($i)->getMessages()); ?></p>
            <?php endforeach; ?>
        </bloquenote>
        <?php endif;?>
        <?php echo $this->form()->openTag($form); ?>
        <ul class="ladoalado">
            <li><?php echo $this->formLabel($form->get('senha')); ?><?php echo $this->formElement($form->get('senha')); ?></li>
            <li><?php echo $this->formSubmit($form->get('enviar')); ?></li>
        </ul>
        <?php echo $this->form()->closeTag(); ?>
    </article>  
</div>