<?php if($this->msg[0]->status) { ?>
    <p>Seja muito bem vindo ao nosso captura.me</p>
    <p>Agora estás dentro do maior portal de fotografias livres do mundo!</p>
    <p>O Processo de validação do usuário foi executado com sucesso onde está acima a respostado processo de ativação, todos do captura.me agradecem sua cooperação!</p>
    <p>Desejamos sempre para você Boas capturadas!</p>
    <p>Aguardamos ansiosos pelos seus materiais fotográficos!</p>
<?php } else { ?>
   <p>Seu usuário já foi ativado, é possível agora disfrutar de todas as vantagens de ser um capturador!</p>
   <p>Vá até na cozinha, pegue sua bebida favorita, faça algumas pipocas e aproveite ao maximo o captura.me!</p>
   <p>Desejamos que sempre para você Boas capturadas!</p>   
<?php }?>

