<?php $this->tituloHelper()->setTitulo('Adicionar Revista'); ?>
<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Adicionar Revista</h2>
        <h2 class='subtitulo'>Adicionando uma nova revista no Captura.Me</h2>
    </bloquenote>
    <article>
        <?php $form = $this->form;  $form->setAttribute('action', $this->url('adicionar-revista')); $form->prepare(); ?>
        <?php if($form->getMessages()): ?>
        <bloquenote>
            <?php foreach($form->getMessages() as $i => $element): ?>
                <p><?php echo "Erro: [" . $this->formLabel($form->get($i)) . '] ' .  implode(', ', $form->get($i)->getMessages()); ?></p>
            <?php endforeach; ?>
        </bloquenote>
        <?php endif;?>
        <?php echo $this->form()->openTag($form); ?>
        <ul class="ladoalado">
            <li><?php echo $this->formLabel($form->get('titulo')); ?><?php echo $this->formElement($form->get('titulo')); ?></li>
            <li><?php echo $this->formLabel($form->get('arquivo')); ?><?php echo $this->formElement($form->get('arquivo')); ?></li>
            <li><?php echo $this->formLabel($form->get('descricao')); ?><?php echo $this->formElement($form->get('descricao')); ?></li>
            <li><?php echo $this->formSubmit($form->get('enviar')); ?></li>
        </ul>
        <?php echo $this->form()->closeTag(); ?>
    </article>  
</div>