<?php $this->view->headScript()->prependFile('/js/application/index/busca.js');  ?> 
 
<ul id="menuBusca">
    <li id="filtroEventos">Eventos <span id="iconEventos">&nbsp;</span></li>
    <li><span class="separadorPequeno">&nbsp;</span></li>
    <li id="filtroTags">Tags <span id="iconTags">&nbsp;</span></li>
    <li><span id="separadorMenuBusca">&nbsp;</span></li>
</ul>   

<div id="divPesquisa" class="scroll-pane escondido" >
    <ul id="resultadoPesquisa" class="filtroEventos">
    </ul>
</div> 