<?php if (!$this->me){ ?>
<ul>
<li><a href="<?php echo $this->loginUrl; ?>"><span style="color: white; display: inline-block; font-size: 16px; font-weight: bold; background: none repeat scroll 0px 0px rgb(198, 198, 198); width: auto; vertical-align: top; padding: 2px 5px; margin: 0px; height: 16px;">Informar </span>
    <img src="http://static.ak.fbcdn.net/rsrc.php/zB6N8/hash/4li2k73z.gif">
</a></li>
</ul>
<?php } else { ?>
<ul><li><img src="http://static.ak.fbcdn.net/rsrc.php/zB6N8/hash/4li2k73z.gif"><span style="background: none repeat scroll 0px 0px rgb(31, 255, 48); vertical-align: middle; font-weight: bold; font-size: 17px; color: white; height: 18px; width: 30px; display: inline-block; margin: 0px; padding: 1px 0px;">OK</span></li></ul>
<?php } ?>