<?php foreach ($this->timeline as $line): ?>
<div class='parteConteudo'>
    <?php 
        switch ($line->id_tipo)
        {
            case 1 : $tipo = 'novidade'; break;
            case 2 : $tipo = 'dica'; break;
            case 4 : $tipo = 'revista'; break;
            
            case 5 : $tipo = 'batalha'; break;
            case 6 : $tipo = 'video'; break;
            case 7 : $tipo = 'evento'; break;
            default: $tipo = 'menu';
        }
    ?>
    <bloquenote class="<?php echo $tipo; ?>">
        <h2 class='titulo'><?php echo $line->titulo; ?></h2>
        <h2 class='subtitulo'><?php echo $line->getData(); ?> <?php echo $line->getHora(); ?></h2>
    </bloquenote>
    <article class="conteudoDefault">
        <p><?php echo $line->conteudo; ?></p>
        <?php if($line->link): ?>
            <span class="download">
                <label class="negrito">Download:</label> <a href="<?php echo "{$line->link}"; ?>" ><?php echo $line->titulo; ?></a>
            </span>
        <?php endif; ?>
    </article>
</div>
<?php endforeach; ?>