<?php $this->tituloHelper()->setTitulo('Duvidas?'); ?>

<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Batalhas</h2>
        <h2 class='subtitulo'>O que são Batalhas?</h2>
    </bloquenote>
    <article>
        <span class="bloco">
            <span>As batalhas são um conjunto de fotos de um determinado tema que foi previamente apresentado, possui finalidade de pontuar, divulgar e classificar os melhores fotógrafos do portal “captura.me”, gerando assim mais prestígio aos capturadores.</span>
            <span>Denominada "guerra entre cliques" se apresenta como matriz incentivadora de envio de fotos fantásticas. Este módulo possui como finalidade principal, separar as melhores fotos de acordo com os temas requisitados, gerando assim uma grande lista de fotos brilhantes para que em qualquer momento possa ser fonte de inspiração para outras pessoas.</span>
            <span>Para cada batalha serão selecionadas as 5 melhores fotos, onde as mesmas farão parte da composição inicial do site.</span>
        </span>
        
        <h3 class="paragrafoTitulo">Composição</h3>
        <span class="bloco">
            <ul>
                <li>Título (sobre o tema)</li>
                <li>Descrição (dos itens aceitos em cada batalha)</li>
                <li>Listagem das fotos enviadas para a batalha</li>
            </ul>
        </span>
        
        <h3 class="paragrafoTitulo">Nomenclatura de votação</h3>
        <span class="bloco">
            <ul>
                <li>“Peguei” é o voto POSITIVO na imagem que o usuário gostou. (É chamado assim, pois ao votar na captura, abre-se a opção de baixar a imagem para utilização em “Creative Commons”);</li>
                <li>“Não peguei” é o voto NEGATIVO de uma imagem que o usuário não gostou.</li>
            </ul>
        </span>
        
        <h3 class="paragrafoTitulo">Usuário Logado</h3>
        <span class="bloco">
            <ul>
                <li>« Peguei » vale 100 pontos</li>
                <li>Pode enviar uma foto para batalha;</li>
                <li>É possível comentar na foto;</li>
                <li>Tem direito a um voto para cada foto da batalha.</li>
            </ul>
        </span>
        
        <h3 class="paragrafoTitulo">Usuário Não Logado</h3>
        <span class="bloco">
            <ul>
                <li>Pode votar nas fotos da batalha, acrescentando no contador se “pegou” ou “não pegou” a imagem; </li>
                <li>Na batalha, “Peguei” vale 1 ponto.</li>
            </ul>
        </span>
    </article>
</div>
<p>&nbsp;</p>

<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Capturadores</h2>
        <h2 class='subtitulo'>Classificação de um usuário no Captura.Me</h2>
    </bloquenote>
    <article>
    
        <h3 class="paragrafoTitulo">Capturador</h3>
        <span class="bloco">
            <span>Primeiro nível de um usuário no site, este nível permite ter algumas vantagens que os visitantes não possuem, tais como:</span>
            <ul>
                <li>« Peguei » vale 100 pontos</li>
                <li>Pode enviar uma foto para batalha;</li>
                <li>É possível comentar na foto;</li>
                <li>Tem direito a um voto para cada foto da batalha.</li>
            </ul>
        </span>
        
        <h3 class="paragrafoTitulo">Capturador Bronze</h3>
        <span class="bloco">
            <span>Nível de um usuário que já possúi <b>100 fotos</b>, por ser um usuário com participação ativa o mesmo já começa a ter algumas vantagens interessantes:</span>
            <ul>
                <li>Tem todos os direitos dos usuário precedentes;</li>
                <li>« Peguei » vale 200 pontos</li>
                <li>Tem direito a disfrutar de vantagens em descontos em pontos que o captura.me é conveniado</li>
            </ul>
        </span>
        
        <h3 class="paragrafoTitulo">Capturador Prata</h3>
        <span class="bloco">
            <span>Nível de um usuário que já possúi <b>400 fotos</b>, por ser um usuário com participação importante para o site, o mesmo é considerado muito importante para a comunidade e por ter essa importância ganha algumas vantagens especiais:</span>
            <ul>
                <li>Tem todos os direitos dos usuário precedentes;</li>
                <li>« Peguei » vale 300 pontos</li>
                <li>Tem direito a disfrutar de vantagens em descontos em pontos que o captura.me é conveniado, onde por ter chegado nesse nível nossas lojas conveniadas estão preparadas para aumentarem as vantagens comparadas ao <b>Capturador Bronze</b>.</li>
            </ul>
        </span>
                
        <h3 class="paragrafoTitulo">Capturador Ouro</h3>
        <span class="bloco">
            <span>Nível de um usuário que já possúi <b>1000 fotos</b>, usuário que podemos considerar um que realmente veste a camisa do captura.me, o mesmo ganha um prestígio maior em nossas vantagens:</span>
            <ul>
                <li>Tem todos os direitos dos usuário precedentes;</li>
                <li>« Peguei » vale 500 pontos</li>
                <li>Tem direito a disfrutar de vantagens em descontos em pontos que o captura.me é conveniado, onde por ter chegado nesse nível nossas lojas conveniadas estão preparadas para aumentarem as vantagens comparadas ao <b>Capturador Prata</b>.</li>
                <li>Ao chegar nessa classificação é enviada um prêmio especial para o usuário</li>
            </ul>
        </span>
        
    </article>
</div>