<?php $this->tituloHelper()->setTitulo('Quem Somos?'); ?>
<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Quem Somos</h2>
        <h2 class='subtitulo'></h2>
    </bloquenote>
    <article>
        <span>Uma comunidade de amantes da fotografia que "curtem" capturar uma bela imagem.</span>
        <span>Acreditamos que a partilha do conhecimento é a melhor forma de engrandecer o fotografo, sendo ele amador ou profissional.</span>
    </article>
</div>
<p>&nbsp;</p>
<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Nossa Filosofia</h2>
        <h2 class='subtitulo'></h2>
    </bloquenote>
    <article>
        <span>Seguimos a filosofia do “Creative Commons”, que possibilita a utilização de fotos, com a finalidade de divulgar o autor. Não sendo possível a exploração comercial, de acordo com a licença “by-nc”, que permite: </span>
           <ul>
               <li>Adaptar ou criar obras derivadas sobre a foto licenciada;</li>
               <li>Impossibilitar o uso com fins comerciais;</li>
               <li>Conter menção ao autor nas novas obras e nos créditos.</li>
           </ul>
        <span>Mais informações sobre as licenças em “Creative Commons”, acesse <a href="http://creativecommons.org/licenses/?lang=pt_BR">licença</a></span>
    </article>
</div>
<p>&nbsp;</p>
<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>O que desejamos</h2>
        <h2 class='subtitulo'></h2>
    </bloquenote>
    <article>
        <span>Despertar suas habilidades fotográficas, através da observação de outras técnicas. Descobrir novos olhares e compartilhar ideias, pois elas são “únicas e especiais”. E por mais que você não se considere o melhor do mundo nós do “Captura.me” valorizamos o quanto você é especial.</span>
        <span>Habilidades escondidas associadas a técnicas comuns são o conjunto perfeito para que essa comunidade cresça forte e criativa, e esperamos que todos tenham em mente, frases do tipo:</span>
        <ul>
            <li>“Que ângulo peculiar...”</li>
            <li>“Nunca pensei em ver dessa forma...”</li>
            <li>“Que imagem magnífica!”</li>
            <li>“Hoje consegui ficar inspirado...”</li>
        </ul>
    </article>
</div>
<p>&nbsp;</p>
<div class='parteConteudo'>
    <bloquenote class="menu">
        <h2 class='titulo'>Porque existimos?</h2>
        <h2 class='subtitulo'></h2>
    </bloquenote>
    <article>
        <span>Acreditamos que uma fotografia não deve ser “batida”, mas realmente capturada. E esse processo consiste em pensar na imagem final, procurar o ângulo correto e desenhar “no cérebro” a nossa visão do mundo.</span>
        <span>Divulgar os melhores fotógrafos em nosso meio e lançar novos prodígios. Sendo o mais legal, a descoberta de pessoas que desconheciam “ter um olhar diferente”.</span>
    </article>
</div>
<p>&nbsp;</p>