<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                                            => __DIR__ . '/Module.php',
    'User\Entity\User'                                       => __DIR__ . '/src/User/Entity/User.php',
    'User\Controller\UserController'                         => __DIR__ . '/src/User/Controller/UserController.php',
    'User\Entity\ClassConfig'                                => __DIR__ . '/src/User/Entity/ClassConfig.php',
//     'User\Form\validators\CpfValidator'                     => __DIR__ . '/src/User/Form/validators/CpfValidator.php',
    'User\Form\Register'                                     => __DIR__ . '/src/User/Form/Register.php',
//     'User\Form\LoginFilter'                                  => __DIR__ . '/src/User/Form/LoginFilter.php',
//     'User\Form\RegisterFilter'                               => __DIR__ . '/src/User/Form/RegisterFilter.php',
//     'User\Form\Login'                                        => __DIR__ . '/src/User/Form/Login.php',
//     'User\Form\Base'                                         => __DIR__ . '/src/User/Form/Base.php',

//     'User\Validator\NoRecordExists'                          => __DIR__ . '/src/User/Validator/NoRecordExists.php',
//     'User\Validator\AbstractRecord'                          => __DIR__ . '/src/User/Validator/AbstractRecord.php',
//     'User\Validator\RecordExists'                            => __DIR__ . '/src/User/Validator/RecordExists.php',

     'User\View\Helper\UserLoginWidget'                    => __DIR__ . '/src/User/View/Helper/UserLoginWidget.php',
//     'User\Mapper\UserHydrator'                               => __DIR__ . '/src/User/Mapper/UserHydrator.php',
//     'User\Mapper\UserInterface'                              => __DIR__ . '/src/User/Mapper/UserInterface.php',
//     'User\Mapper\User'                                       => __DIR__ . '/src/User/Mapper/User.php',

);
