<?php
use User\Entity\ClassConfig;
use \User\Auth\CapturaAuth;
echo $this->doctype(); 
?>

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <?php echo $this->headTitle($this->translate('Captura.Me - Você está batalhando!'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Os css-->
        <?php echo $this->headLink(array(
                       'rel' => 'shortcut icon', 
                       'type' => 'image/vnd.microsoft.icon', 
                       'href' => $this->basePath() . '/images/favicon.ico'
                   ))
                   ->prependStylesheet($this->basePath() . '/css/reset.css')
                   ->prependStylesheet($this->basePath() . '/css/batalhando_style.css')
                   ->prependStylesheet($this->basePath() . '/css/default_style.css')
                   ->prependStylesheet($this->basePath() . '/css/editor.css')
                   ->prependStylesheet($this->basePath() . '/js/plugins/jquery/jquery.jscrollpane.css')
                   ->prependStylesheet($this->basePath() . '/js/plugins/lightbox/css/lightbox.css')
                   
                   // falta saber quais desses vão embora
                   ->prependStylesheet($this->basePath() . '/js/plugins/jqueryui/jquery-ui-1.9.2.custom.min.css')
                   ->prependStylesheet($this->basePath() . '/js/plugins/cute/css/main.css')
                   ->prependStylesheet($this->basePath() . '/js/plugins/cute/css/slider-style.css')
                   ->prependStylesheet($this->basePath() . '/js/plugins/multiupload/css/style.css')
             ;
             $usuarioLogado = CapturaAuth::getInstance()->getUser();
        ?>
        
        <?php echo $this->loadCapturadaHelper(); ?>
        <script type="text/javascript">
            var _gaq = _gaq || [];
                _gaq.push(['_setAccount', 'UA-36552941-1']);
                _gaq.push(['_trackPageview']);
                (function() {
                     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();
        
        </script>
        
	</head>
	<body id="batalhando">

          <header align="center">
            <nav>
                <div class="backgroundVermelho"><a id="botaoCapturaHeader" title="Clique para abrir o menu">C</a></div>
                <?php echo $this->tituloHelper()->html(); ?>
                <div id="buscaCaptura" title="Pesquisar evento ou tag">
                    <span id="iconLupa">&nbsp;</span><input class="busca" name="busca" /><input type="hidden" id="valorBusca" />
                 </div>
                <ul id="menuPrincipal">
                    <li><a id="home" href="/" title="Página Inicial">Captura.Me</a></li>
                    <li><a id="novosUsuarios" href="/capturadores" title="Nossos Capturadores">&nbsp;</a></li>
                    <li><a id="novasBatalhas" href="/batalhas" title="Nossas Batalhas">&nbsp;</a></li>
                    <li><a id="novasFotos" href="/novas-capturadas/1" title="Lista de novas fotos">&nbsp;</a></li>
                    <li><a id="novidades" href="/" title="Novidades">&nbsp;</a></li>
                    <li><a id="maisCurtidas" href="/mais-curtidas/1" title="As mais curtidas">&nbsp;</a></li>
                </ul>   
            </nav>
        </header>
        
        <section id="corpo">
            <section id="esquerda">
                <aside>&nbsp;
                    <div id="menuFlutuante">
                        <?php echo $this->menuBatalhandoFlutuanteHelper(); ?>
                    </div>
                </aside>
                <section id="painel">
                    <nav class='lateral'>
                        <ul>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                            <li><a href="#">&nbsp;</a></li>
                        </ul>
                        <span id="separadorListaCapturadas">&nbsp;</span>
                        <a id="empilharFoto" href="#" ></a>
                    </nav>
                        <div id="divisaoEsquerda">
                            <?php if(!preg_match('/\/visualizar-capturada\//', $this->uri)): ?>
                            <aside>
                                <a id="logoHome" href="/" title="Página inicial">&nbsp;</a>
                                <?php echo $this->loginHelper($usuarioLogado, $this->form()); ?>
                                <p id="separador">&nbsp;</p>
                                <ul id="menuAcoesAnuncio">
                                    <li>Anuncios</li>
                                    <li><span class="separadorPequeno">&nbsp;</span></li>
                                    <li><a id="adicionarAnuncio" href="/adicionar-apoio">+ Adicionar</a></li>
                                    <li><span id="separadorMenuAnuncio" class="filtroTag"> </span></li>
                                </ul>
                                <span id="infoAnuncio">
                                </span>
                                <span class="linhaMenuLateral"></span>
                                
                            </aside>
                            <?php endif; ?>
                            <section id="conteudo">
                                <article><div class="escondido">Creative Commons <b>CC BY-ND</b>: <br>Possível utilização da imagem caso informe <b>quem é autor</b> e <b>não altere a imagem</b>.<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div></article>
                                <div id="blocoMenuRapido">
                                </div>
                                <div id="blocoConteudo">
                                   <?php echo $this->content; ?>
                                   <p class="bugfixespacamento">&nbsp;</p>
                                </div>
                            </section>
                            <p class="bugfixespacamento">&nbsp;</p>
                        </div>
                </section>
                
            </section>
            
            <aside id="direita">
                <?php echo $this->msgHelper(); ?>
                <nav>
                    <?php //echo $this->buscaHelper(); ?>
                </nav>
            </aside>
            
        </section> 
        <?php echo $this->msgSobrepostaHelper(); ?>
            
        
        <?php  
               $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                          ->prependFile($this->basePath() . '/js/index.js')
                          
                          // Testar para ver quem vai sair agora
                          ->prependFile($this->basePath() . '/js/jquery.fileDownload.js')
                          ->prependFile($this->basePath() . '/js/plugins/multiupload/js/multiupload.js')
//                           ->prependFile($this->basePath() . '/js/plugins/tweet/jquery.tweet.js')
                          ->prependFile($this->basePath() . '/js/plugins/mask/jquery.maskedinput-1.3.min.js')
                          
                          
                          ->prependFile($this->basePath() . '/js/plugins/jquery/jquery.elastic.source.js')
                          ->prependFile($this->basePath() . '/js/plugins/jquery/jquery.jscrollpane.min.js')
                          ->prependFile($this->basePath() . '/js/plugins/jquery/mwheelIntent.js')
                          ->prependFile($this->basePath() . '/js/plugins/jquery/jquery-mousewheel.js')
                          ->prependFile($this->basePath() . '/js/plugins/jqueryui/jquery-ui-custom.min.js')
//                           ->prependFile($this->basePath() . '/js/plugins/jquery/jquery-ui.js') //testar para saber qual dos dois vai ficar
                          
                          ->prependFile($this->basePath() . '/js/plugins/jquery/jscrollpane.captura.js')
                          ->prependFile($this->basePath() . '/js/plugins/lightbox/lightbox.destaque.js')
                          ->prependFile($this->basePath() . '/js/plugins/lightbox/lightbox.js')
//                           ->prependFile($this->basePath() . '/js/plugins/jquery/jquery-migrate-1.2.1.min.js')
                          ->prependFile($this->basePath() . '/js/plugins/jquery/jquery.js')
              ;
              
              if($this->class && is_dir(constant('JS') . $this->class->getJsPath())){
                  $jsAction = $this->basePath('/js/') . $this->class->getJsPath() . "{$this->layout()->action}.js";
                  $this->headScript()->appendFile($jsAction, 'text/javascript');
              }
              
              echo $this->headScript();
               
         ?>
         
         <div id="dialog" class="escondido">&nbsp;</div>
<!--         <div id='centralizandoLightbox'> -->
            <div id='capturalightbox'></div>
<!--         </div> -->
	</body>
</html>
