<?php use User\Auth\CapturaAuth; ?>
<?php $this->headScript()->prependFile('/js/plugins/lightbox/lightbox.batalha.js');  ?>
<?php $this->tituloHelper()->setTitulo('Batalha'); ?>
<div class='parteConteudo'>
    <bloquenote class="menu"><h2 class='titulo'><?php echo $this->batalhaCapturada[0]->batalha->titulo; ?></h2></bloquenote>
    <article>
        <h3 class="paragrafoTitulo">&nbsp;</h3>
        
        <?php echo $this->paginadorHelper("/visualizar-batalha/{$this->batalhaCapturada[0]->id_batalha}/", $this->totalPaginas, $this->pagina); ?>
        
        <?php if($this->batalhaCapturada):?>
        <article class="listagemImagens">
            <?php $tamanho = count($this->batalhaCapturada); for($i=0; $i< $tamanho; $i += 5): ?>
            <ul class="listaCapturadas">
                <?php for($indice = $i; $indice < $i+5; $indice++): ?>
                    <?php if(array_key_exists($indice, $this->batalhaCapturada)){ ?>
                    <li>
                        <a href="<?php echo $this->batalhaCapturada[$indice]->capturada->getImagem(); ?>" rel="lightbox[listaCapturadas]" class="capturada_<?php echo $indice+1; ?>" >
                           <?php if($this->batalhaCapturada[$indice]->capturada->descricao): ?>
                               <span class='description'><?php echo $this->batalhaCapturada[$indice]->capturada->descricao; ?></span>
                           <?php endif; ?>
                           <span class='view'><?php echo $this->batalhaCapturada[$indice]->capturada->getImagem(); ?></span>
                           <span class='exif'>
                               <input type="hidden" class="iso" value="<?php echo $this->batalhaCapturada[$indice]->capturada->getExif()->getIso(); ?>">
                               <input type="hidden" class="exposicao" value="<?php echo $this->batalhaCapturada[$indice]->capturada->getExif()->getExposicao(); ?>">
                               <input type="hidden" class="distanciafocal" value="<?php echo $this->batalhaCapturada[$indice]->capturada->getExif()->getDistanciafocal(); ?>">
                               <input type="hidden" class="abertura" value="<?php echo $this->batalhaCapturada[$indice]->capturada->getExif()->getAbertura(); ?>">
                               <input type="hidden" class="flash" value="<?php echo $this->batalhaCapturada[$indice]->capturada->getExif()->getFlash(); ?>">
                           </span>
                           <input type="hidden" class="identitem" value="<?php echo $this->batalhaCapturada[$indice]->id_batalha_capturada; ?>">
                           <input type="hidden" class="data" value="<?php echo $this->batalhaCapturada[$indice]->id_usuario . '_' . $this->batalhaCapturada[$indice]->capturada->id_capturada; ?>">
                           <input type="hidden" class="pegou" value="<?php echo $this->batalhaCapturada[$indice]->pegou . '_' . $this->batalhaCapturada[$indice]->naoPegou; ?>">
                           <input type="hidden" class="title" value="<?php echo $this->batalhaCapturada[$indice]->capturada->nome; ?>">
                           <img src="<?php echo $this->batalhaCapturada[$indice]->capturada->getThumb(); ?>">
                           <?php foreach($this->batalhaCapturada[$indice]->capturada->tags as $tag): ?>
                               <input type="hidden" class="tag_<?php echo $this->batalhaCapturada[$indice]->capturada->id_capturada . '_' . $tag->id_tag; ?>" value="<?php echo $this->batalhaCapturada[$indice]->capturada->id_capturada . '_' . $tag->id_tag . '_' . $tag->nome. '_'  . $this->batalhaCapturada[$indice]->capturada->user; ?>" >
                           <?php endforeach; ?>
                        </a>
                    </li>
                    <?php } ?>
                <?php endfor;?>
                <li class="linhaDivisoria">&nbsp;</li>
            </ul>
            <?php endfor; ?>
            </article>
        <?php endif; ?>
        
    </article>  
</div>





