<h2 class="linha linhaTitulo pointer"><span class="branco">Enviar </span><span class="branco">Capturada(s)</span></h2>
<div class="paragrafos">
    <div class="paragrafoCentral">
   
        <div class="paragrafoDados">
            <div class="cinza">
                <span class="iconMais">&nbsp;</span><a id="btnAddTag" class="pointer">Tags: </a> <input type="text" id="addTag" />
            </div>
        </div>
       
        <div id="dragAndDropFiles" class="uploadArea">
	        <h1>Arraste Imagens para aqui</h1>
        </div>
        <form name="multiplasCapturadas" id="multiplasCapturadas" enctype="multipart/form-data">
            <input type="file" name="arquivo" id="arquivo" multiple class="escondido"/>
            <input type="button" id="selecionar" value="Selecionar Imagens" class="buttonUpload" />
            <input type="submit" name="submitHandler" id="submitHandler" value="Enviar" class="buttonUpload" />
        </form>
        <div class="progressBar">
            <div class="status"></div>
        </div>
    </div>
    <br class="clear" />
    <h2 class="linha linhaTitulo pointer"><span class="verde">Envio de </span><span class="verdeClaro">uma Capturada</span></h2>
    <div class="paragrafoCentral">
        <span>Forma mais elemental de ajudar a comunidade sem falar necessária.</span>
        <span>Ao enviar uma foto além de contribuir para que nossa base de dados <b>livres</b> cresça, estarás recenedo um aumento na sua pontuação um acréssimo de <b>1 ponto por cada foto enviada</b>.</span>
    </div>
</div>
<br class="clear" />