<?php $this->tituloHelper()->setTitulo('Novas Capturadas'); ?>
<?php $this->headScript()->prependFile('/js/plugins/lightbox/lightbox.comum.js');  ?> 

<div class='parteConteudo'>
    <bloquenote class="novasCapturadas">
        <h2 class='titulo'>Novas Capturadas</h2>
        <h2 class='subtitulo'>As capturadas mais recentes no Captura.Me</h2>
    </bloquenote>
    <article>
        <?php echo $this->paginadorHelper("/novas-capturadas/", $this->totalPaginas, $this->pagina); ?>
        
        <?php if($this->capturadas):?>
        <article class="listagemImagens">
            <?php $tamanho = count($this->capturadas); for($i=0; $i< $tamanho; $i += 5): ?>
            <ul class="listaCapturadas">
                <?php for($indice = $i; $indice < $i+5; $indice++): ?>
                    <?php if(array_key_exists($indice, $this->capturadas)){ ?>
                    <li>
                        <a href="<?php echo $this->capturadas[$indice]->getImagem(); ?>" rel="lightbox[listaCapturadas]" class="capturada_<?php echo $indice+1; ?>">
                           <?php if($this->capturadas[$indice]->descricao): ?>
                               <span class='description'><?php echo $this->capturadas[$indice]->descricao; ?></span>
                           <?php endif; ?>
                           <span class='view'><?php echo $this->capturadas[$indice]->getImagem(); ?></span>
                           <span class='exif'>
                               <input type="hidden" class="iso" value="<?php echo $this->capturadas[$indice]->getExif()->getIso(); ?>">
                               <input type="hidden" class="exposicao" value="<?php echo $this->capturadas[$indice]->getExif()->getExposicao(); ?>">
                               <input type="hidden" class="distanciafocal" value="<?php echo $this->capturadas[$indice]->getExif()->getDistanciafocal(); ?>">
                               <input type="hidden" class="abertura" value="<?php echo $this->capturadas[$indice]->getExif()->getAbertura(); ?>">
                               <input type="hidden" class="flash" value="<?php echo $this->capturadas[$indice]->getExif()->getFlash(); ?>">
                           </span>
                           <input type="hidden" class="identitem" value="<?php echo $this->capturadas[$indice]->id_capturada . '_' . $this->capturadas[$indice]->user; ?>">
                           <input type="hidden" class="data" value="<?php echo $this->capturadas[$indice]->user. '_' . $this->capturadas[$indice]->id_capturada; ?>">
                           <input type="hidden" class="pegou" value="<?php echo $this->capturadas[$indice]->pegou . '_' . $this->capturadas[$indice]->naoPegou; ?>">
                           <input type="hidden" class="title" value="<?php echo $this->capturadas[$indice]->nome; ?>">
                           <img src="<?php echo $this->capturadas[$indice]->getThumb(); ?>">
                           <?php foreach($this->capturadas[$indice]->tags as $tag): ?>
                               <input type="hidden" class="tag_<?php echo $this->capturadas[$indice]->id_capturada . '_' . $tag->id_tag; ?>" value="<?php echo $this->capturadas[$indice]->id_capturada . '_' . $tag->id_tag . '_' . $tag->nome . '_' . $this->capturadas[$indice]->user; ?>" >
                           <?php endforeach; ?>
                        </a>
                    </li>
                    <?php } ?>
                <?php endfor;?>
                <li class="linhaDivisoria">&nbsp;</li>
            </ul>
            <?php endfor; ?>
            </article>
        <?php endif; ?>
    </article>  
</div>
