<?php $this->headScript()->prependFile('/js/plugins/lightbox/lightbox.comum.js');  ?>
<?php $this->tituloHelper()->setTitulo(\captura::rulleSplitName($this->tag->getNome())); ?>

<div class='parteConteudo'>
    <bloquenote class="menu"><h2 class='titulo'>Tags</h2></bloquenote>
    <article>
        <h3 class="paragrafoTitulo"><?php echo \captura::rulleSplitName($this->tag->getNome()); ?></h3>
        <?php echo $this->paginadorHelper("/tag/{$this->tag->getNome()}/", $this->totalPaginas, $this->pagina); ?>
        <?php if($this->capturadas):?>
            <article class="listagemImagens">
                <?php $tamanho = count($this->capturadas); for($i=0; $i< $tamanho; $i += 5): ?>
                <ul class="listaCapturadas">
                    <?php for($indice = $i; $indice < $i+5; $indice++): ?>
                        <?php if(array_key_exists($indice, $this->capturadas)){ ?>
                        <li>
                            <a href="<?php echo $this->capturadas[$indice]->capturada->getImagem(); ?>" rel="lightbox[listaCapturadas]" class="capturada_<?php echo $indice+1; ?>">
                               <?php if($this->capturadas[$indice]->capturada->descricao): ?>
                                   <span class='description'><?php echo $this->capturadas[$indice]->capturada->descricao; ?></span>
                               <?php endif; ?>
                               <span class='view'><?php echo $this->capturadas[$indice]->capturada->getImagem(); ?></span>
                               <span class='exif'>
                                   <input type="hidden" class="iso" value="<?php echo $this->capturadas[$indice]->capturada->getExif()->getIso(); ?>">
                                   <input type="hidden" class="exposicao" value="<?php echo $this->capturadas[$indice]->capturada->getExif()->getExposicao(); ?>">
                                   <input type="hidden" class="distanciafocal" value="<?php echo $this->capturadas[$indice]->capturada->getExif()->getDistanciafocal(); ?>">
                                   <input type="hidden" class="abertura" value="<?php echo $this->capturadas[$indice]->capturada->getExif()->getAbertura(); ?>">
                                   <input type="hidden" class="flash" value="<?php echo $this->capturadas[$indice]->capturada->getExif()->getFlash(); ?>">
                               </span>
                               <input type="hidden" class="identitem" value="<?php echo $this->capturadas[$indice]->capturada->id_capturada . '_' . $this->capturadas[$indice]->capturada->user; ?>">
                               <input type="hidden" class="data" value="<?php echo $this->capturadas[$indice]->capturada->user. '_' . $this->capturadas[$indice]->capturada->id_capturada; ?>">
                               <input type="hidden" class="pegou" value="<?php echo $this->capturadas[$indice]->capturada->pegou . '_' . $this->capturadas[$indice]->capturada->naoPegou; ?>">
                               <input type="hidden" class="title" value="<?php echo $this->capturadas[$indice]->capturada->nome; ?>">
                               <img src="<?php echo $this->capturadas[$indice]->capturada->getThumb(); ?>">
                               <?php foreach($this->capturadas[$indice]->capturada->tags as $tag): ?>
                                   <input type="hidden" class="tag_<?php echo $this->capturadas[$indice]->capturada->id_capturada . '_' . $tag->id_tag; ?>" value="<?php echo $this->capturadas[$indice]->capturada->id_capturada . '_' . $tag->id_tag . '_' . $tag->nome . '_' . $this->capturadas[$indice]->capturada->user; ?>" >
                               <?php endforeach; ?>
                            </a>
                        </li>
                        <?php } ?>
                    <?php endfor;?>
                    <li class="linhaDivisoria">&nbsp;</li>
                </ul>
                <?php endfor; ?>
            </article>
        <?php endif; ?>
    </article>  
</div>